# Generated by Django 4.1.13 on 2024-05-26 20:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="descprtion",
            new_name="description",
        ),
    ]
