# Generated by Django 4.1.13 on 2024-06-25 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='firts_name',
            new_name='first_name',
        ),
    ]
